import StyleDictionary from 'style-dictionary';
import { readFileSync, writeFileSync, readdirSync } from 'fs';
import { makeResolver } from './lib/resolve-token.mjs';

// Token axis contract — enforced at build time.
// Mode axis owns lighting: background, text, border, feedback.
// Expression axis owns personality: accent, border-radius.
// Keeping them separate means both can be active simultaneously with no cascade conflict.
const TOKEN_CONTRACTS = {
  mode: [
    'color-surface-',
    'color-curtain',
    'color-text-',
    'color-border-',
    'color-feedback-',
    'color-neutral-',
    'color-accent-',
    'button-secondary-',
    'checkbox-',
    'radio-',
    'switch-',
    'textarea-',
  ],
  expression: [
    'color-accent-',
    'border-radius-',
    'button-border-radius',
    'card-border-radius',
    'input-border-radius',
    'select-border-radius',
  ],
};

function validateTokenContract(filePath, axis) {
  const allowed = TOKEN_CONTRACTS[axis];
  const tokens = JSON.parse(readFileSync(filePath, 'utf8'));
  const violations = Object.keys(tokens).filter(
    key => !allowed.some(prefix => key.startsWith(prefix))
  );
  if (violations.length > 0) {
    throw new Error(
      `[token contract] "${axis}" axis violation in ${filePath}.\n` +
      `These tokens are not allowed on this axis: ${violations.join(', ')}\n` +
      `Mode axis owns: surface, text, border, feedback.\n` +
      `Expression axis owns: accent, border-radius.`
    );
  }
}

// Patch size/rem to skip complex CSS functions (clamp, min, max, calc).
// SD5's built-in throws when parseFloat() hits a non-numeric value like clamp().
StyleDictionary.registerTransform({
  name: 'size/rem',
  type: 'value',
  filter: (token, options) => {
    const type = options?.usesDtcg ? token.$type : token.type;
    return type === 'dimension' || type === 'fontSize';
  },
  transform: (token, _, options) => {
    const raw = options?.usesDtcg ? token.$value : token.value;
    const str = String(raw ?? '');
    if (/^(clamp|min|max|calc|env|var)\(/.test(str)) return str;
    const unitMatch = str.match(/[a-zA-Z%]+$/);
    const unit = unitMatch?.[0];
    const num = parseFloat(str);
    if (isNaN(num)) return str;
    if (num === 0) return '0';
    return unit ? `${num}${unit}` : `${num}rem`;
  },
});

StyleDictionary.registerFormat({
  name: 'css/brand-variables',
  format: ({ dictionary, options }) => {
    const { brand, selector: selectorOverride, colorScheme } = options;
    const selector = selectorOverride ?? (brand === 'portfolio' ? ':root' : `[data-brand="${brand}"]`);
    const extra = colorScheme ? `  color-scheme: ${colorScheme};\n` : '';
    const vars = dictionary.allTokens
      .map(token => {
        // preserveSemanticRefs: emit `var(--ref)` instead of the resolved value when
        // the token references another semantic token (kebab ref, no dot). Used by the
        // bold build so mode-owned indirection tokens (e.g. color-accent-bold, flipped
        // by dark.css) resolve per-mode in the cascade instead of being baked in.
        const original = options.usesDtcg ? token.original?.$value : token.original?.value;
        if (options.preserveSemanticRefs && typeof original === 'string') {
          const ref = original.match(/^\{([a-z0-9-]+)\}$/);
          if (ref && !ref[1].includes('.')) return `  --${token.name}: var(--${ref[1]});`;
        }
        return `  --${token.name}: ${options.usesDtcg ? token.$value : token.value};`;
      })
      .join('\n');
    return `/* Auto-generated by Style Dictionary — do not edit directly */\n/* Brand: ${brand} */\n\n${selector} {\n${extra}${vars}\n}\n`;
  }
});

const portfolio = new StyleDictionary({
  usesDtcg: true,
  source: [
    'tokens/global.json',
    'tokens/components/*.json',
    'tokens/brands/portfolio/tokens.json',
  ],
  platforms: {
    css: {
      transformGroup: 'css',
      prefix: '',
      buildPath: 'styles/brands/',
      files: [{
        destination: 'portfolio.css',
        format: 'css/brand-variables',
        options: {
          brand: 'portfolio',
          // Also targets [data-mode="light"] and [data-expression="default"] so demo panels
          // can explicitly opt into the light/default state even when the site is in dark/bold.
          selector: ':root, [data-mode="light"], [data-expression="default"]',
          // Late-bind semantic references: component tokens like
          // accordion-trigger-color: {color-text-primary} emit as var(--color-text-primary)
          // so they resolve against the active mode/expression scope. Without this they
          // bake in light values and every component token needs a hand-written dark
          // override.
          preserveSemanticRefs: true,
        }
      }]
    }
  }
});

validateTokenContract('tokens/brands/dark/tokens.json', 'mode');
validateTokenContract('tokens/brands/bold/tokens.json', 'expression');
await portfolio.buildAllPlatforms();
console.log('✓ Built portfolio.css');

// Reads and JSON.parses a token file, throwing a message that names the
// file — without this, a malformed tokens/components/*.json surfaces as a
// bare "Unexpected token" with no indication of which file it came from.
function loadTokenJson(path) {
  let raw
  try {
    raw = readFileSync(path, 'utf8')
  } catch (err) {
    throw new Error(`[computeChangedTokens] Could not read ${path}: ${err.message}`)
  }
  try {
    return JSON.parse(raw)
  } catch (err) {
    throw new Error(`[computeChangedTokens] ${path} is not valid JSON: ${err.message}`)
  }
}

// Loaded once and shared by both computeChangedTokens calls below — dark and
// bold otherwise each independently re-read and re-parsed the same set of
// files (tokens/global.json, tokens/brands/portfolio/tokens.json, every file
// in tokens/components/) for identical results.
const globalJsonForDiff = loadTokenJson('tokens/global.json')
const baseJsonForDiff = loadTokenJson('tokens/brands/portfolio/tokens.json')
const componentJsonForDiff = Object.assign(
  {},
  ...readdirSync('tokens/components')
    .filter(f => f.endsWith('.json'))
    .map(f => loadTokenJson(`tokens/components/${f}`))
)
const lightMapForDiff = { ...componentJsonForDiff, ...baseJsonForDiff }

// Axis diff sets — every token whose *resolved* value changes under an axis
// override must be re-declared inside that axis's scope. var() references in
// custom properties substitute on the element where the property is declared,
// so a component token declared on :root bakes in light values for any nested
// [data-mode="dark"] scope (story wrappers, /design-system demo panels) even
// when its value is var(--color-text-primary). Re-declaring the changed token
// on the axis selector makes substitution happen against that scope's cascade.
function computeChangedTokens(overridesPath) {
  const overrides = loadTokenJson(overridesPath)
  const resolveLight = makeResolver(lightMapForDiff, globalJsonForDiff)
  const resolveAxis = makeResolver({ ...lightMapForDiff, ...overrides }, globalJsonForDiff)

  const changed = new Set()
  for (const name of Object.keys(lightMapForDiff)) {
    if (name in overrides) continue // isSource already emits these

    // Composite/object-valued tokens (a future DTCG shadow or typography
    // token) resolve to null from makeResolver, which can't diff them — so
    // rather than silently treat "can't tell" as "unchanged" (which would
    // reintroduce the exact light-value-baked-into-dark-scope bug this
    // function exists to fix, for that token), always re-declare them.
    const rawValue = lightMapForDiff[name].$value ?? lightMapForDiff[name].value
    if (rawValue && typeof rawValue === 'object') {
      changed.add(name)
      continue
    }

    const light = resolveLight(name)
    const axis = resolveAxis(name)
    if (light !== null && axis !== null && light !== axis) changed.add(name)
  }
  return changed
}

const darkChanged = computeChangedTokens('tokens/brands/dark/tokens.json')
const boldChanged = computeChangedTokens('tokens/brands/bold/tokens.json')

const dark = new StyleDictionary({
  usesDtcg: true,
  // Base tokens in `include` so SD understands dark/tokens.json intentionally overrides them.
  // Collision warnings only fire for source-vs-source conflicts; include-vs-source is expected.
  include: [
    'tokens/global.json',
    'tokens/components/*.json',
    'tokens/brands/portfolio/tokens.json',
  ],
  source: [
    'tokens/brands/dark/tokens.json',
  ],
  platforms: {
    css: {
      transformGroup: 'css',
      prefix: '',
      buildPath: 'styles/brands/',
      files: [{
        destination: 'dark.css',
        format: 'css/brand-variables',
        filter: (token) => token.isSource || darkChanged.has(token.name),
        // preserveSemanticRefs keeps re-declared component tokens as var() refs
        // so the dark+bold combination still composes (bold's accent overrides
        // win inside a scope carrying both attributes).
        options: { brand: 'dark', selector: '[data-mode="dark"]', colorScheme: 'dark', preserveSemanticRefs: true }
      }]
    }
  }
});

await dark.buildAllPlatforms();
console.log('✓ Built dark.css');

const bold = new StyleDictionary({
  usesDtcg: true,
  include: [
    'tokens/global.json',
    'tokens/components/*.json',
    'tokens/brands/portfolio/tokens.json',
  ],
  source: [
    'tokens/brands/bold/tokens.json',
  ],
  platforms: {
    css: {
      transformGroup: 'css',
      prefix: '',
      buildPath: 'styles/brands/',
      files: [{
        destination: 'bold.css',
        format: 'css/brand-variables',
        filter: (token) => token.isSource || boldChanged.has(token.name),
        options: { brand: 'bold', selector: '[data-expression="bold"]', preserveSemanticRefs: true }
      }]
    }
  }
});

await bold.buildAllPlatforms();
console.log('✓ Built bold.css');

const { buildTokenReference } = await import('./scripts/build-token-reference.mjs');
buildTokenReference();

const { buildComponentRegistry } = await import('./scripts/build-component-registry.mjs');
buildComponentRegistry();

// Depends on component-registry.json and token-reference.json, both already
// rebuilt above.
const { buildComponentDocs } = await import('./scripts/build-component-docs.mjs');
buildComponentDocs();

const { buildChangelog } = await import('./scripts/build-changelog.mjs');
buildChangelog();

// Must run last: llms.txt compiles from component-registry.json and
// token-reference.json, so both have to exist in their rebuilt form first.
const { buildLlmsTxt } = await import('./scripts/build-llms-txt.mjs');
buildLlmsTxt();
