import StyleDictionary from 'style-dictionary';
import { readFileSync, writeFileSync, readdirSync } from 'fs';
import { makeResolver } from './lib/resolve-token.mjs';

// Token axis contract — enforced at build time.
// Mode axis owns lighting: background, text, border, feedback. Kept separate
// from the semantic/structural tier so a mode override file can't smuggle in
// unrelated tokens (typography, spacing, radii) that belong on the base/brand
// layer instead.
const TOKEN_CONTRACTS = {
  mode: [
    'color-surface-',
    'color-curtain',
    'color-text-',
    'color-border-',
    'color-feedback-',
    'color-neutral-',
    'color-accent-',
    'button-secondary-',
    'checkbox-',
    'radio-',
    'switch-',
    'textarea-',
  ],
};

function validateTokenContract(filePath, axis) {
  const allowed = TOKEN_CONTRACTS[axis];
  const tokens = JSON.parse(readFileSync(filePath, 'utf8'));
  const violations = Object.keys(tokens).filter(
    key => !allowed.some(prefix => key.startsWith(prefix))
  );
  if (violations.length > 0) {
    throw new Error(
      `[token contract] "${axis}" axis violation in ${filePath}.\n` +
      `These tokens are not allowed on this axis: ${violations.join(', ')}\n` +
      `Mode axis owns: surface, text, border, feedback.`
    );
  }
}

// Patch size/rem to skip complex CSS functions (clamp, min, max, calc).
// SD5's built-in throws when parseFloat() hits a non-numeric value like clamp().
StyleDictionary.registerTransform({
  name: 'size/rem',
  type: 'value',
  filter: (token, options) => {
    const type = options?.usesDtcg ? token.$type : token.type;
    return type === 'dimension' || type === 'fontSize';
  },
  transform: (token, _, options) => {
    const raw = options?.usesDtcg ? token.$value : token.value;
    const str = String(raw ?? '');
    if (/^(clamp|min|max|calc|env|var)\(/.test(str)) return str;
    const unitMatch = str.match(/[a-zA-Z%]+$/);
    const unit = unitMatch?.[0];
    const num = parseFloat(str);
    if (isNaN(num)) return str;
    if (num === 0) return '0';
    return unit ? `${num}${unit}` : `${num}rem`;
  },
});

StyleDictionary.registerFormat({
  name: 'css/brand-variables',
  format: ({ dictionary, options }) => {
    const { brand, selector: selectorOverride, colorScheme } = options;
    const selector = selectorOverride ?? `[data-brand="${brand}"]`;
    const extra = colorScheme ? `  color-scheme: ${colorScheme};\n` : '';
    const vars = dictionary.allTokens
      .map(token => {
        // preserveSemanticRefs: emit `var(--ref)` instead of the resolved value when
        // the token references another semantic token (kebab ref, no dot). This is
        // what lets a later layer (portfolio over base, dark over light) override
        // just the primitive it actually changes and have every token that chains
        // through it pick up the new value via the live CSS cascade, instead of
        // baking in whichever layer's value happened to build first.
        const original = options.usesDtcg ? token.original?.$value : token.original?.value;
        if (options.preserveSemanticRefs && typeof original === 'string') {
          const ref = original.match(/^\{([a-z0-9-]+)\}$/);
          if (ref && !ref[1].includes('.')) return `  --${token.name}: var(--${ref[1]});`;
        }
        return `  --${token.name}: ${options.usesDtcg ? token.$value : token.value};`;
      })
      .join('\n');
    return `/* Auto-generated by Style Dictionary — do not edit directly */\n/* Brand: ${brand} */\n\n${selector} {\n${extra}${vars}\n}\n`;
  }
});

// Reads and JSON.parses a token file, throwing a message that names the
// file — without this, a malformed tokens/components/*.json surfaces as a
// bare "Unexpected token" with no indication of which file it came from.
function loadTokenJson(path) {
  let raw
  try {
    raw = readFileSync(path, 'utf8')
  } catch (err) {
    throw new Error(`[computeChangedTokens] Could not read ${path}: ${err.message}`)
  }
  try {
    return JSON.parse(raw)
  } catch (err) {
    throw new Error(`[computeChangedTokens] ${path} is not valid JSON: ${err.message}`)
  }
}

const globalJsonForDiff = loadTokenJson('tokens/global.json')
const componentJsonForDiff = Object.assign(
  {},
  ...readdirSync('tokens/components')
    .filter(f => f.endsWith('.json'))
    .map(f => loadTokenJson(`tokens/components/${f}`))
)
const baseLightJson = loadTokenJson('tokens/brands/base/light.json')
const baseDarkJson = loadTokenJson('tokens/brands/base/dark.json')
const portfolioLightJson = loadTokenJson('tokens/brands/portfolio/tokens.json')
const portfolioDarkJson = loadTokenJson('tokens/brands/portfolio/dark.json')

// Axis diff — every token whose *resolved* value changes under a layer's
// overrides must be re-declared inside that layer's CSS scope. var()
// references in custom properties substitute on the element where the
// property is declared, so a component token declared on an earlier layer
// bakes in that layer's values for any nested scope (story wrappers,
// /design-system demo panels) even when its value is var(--color-text-primary).
// Re-declaring the changed token on the later layer's selector makes
// substitution happen against that scope's cascade.
//
// Takes the already-merged map a layer builds on top of (`baseMap`) and the
// raw overrides object for that layer, rather than a fixed light-vs-dark
// pair — reused for all three override layers (base dark over base light,
// portfolio light over base light, portfolio dark over base+portfolio).
function computeChangedTokens(baseMap, overrides) {
  const resolveBase = makeResolver(baseMap, globalJsonForDiff)
  const resolveAxis = makeResolver({ ...baseMap, ...overrides }, globalJsonForDiff)

  const changed = new Set()
  for (const name of Object.keys(baseMap)) {
    if (name in overrides) continue // isSource already emits these

    // Composite/object-valued tokens (a future DTCG shadow or typography
    // token) resolve to null from makeResolver, which can't diff them — so
    // rather than silently treat "can't tell" as "unchanged" (which would
    // reintroduce the exact stale-value-baked-into-a-later-scope bug this
    // function exists to fix, for that token), always re-declare them.
    const rawValue = baseMap[name].$value ?? baseMap[name].value
    if (rawValue && typeof rawValue === 'object') {
      changed.add(name)
      continue
    }

    const base = resolveBase(name)
    const axis = resolveAxis(name)
    if (base !== null && axis !== null && base !== axis) changed.add(name)
  }
  return changed
}

const baseLightMap = { ...componentJsonForDiff, ...baseLightJson }
const baseDarkChanged = computeChangedTokens(baseLightMap, baseDarkJson)
const portfolioLightChanged = computeChangedTokens(baseLightMap, portfolioLightJson)

const portfolioDarkBaseMap = { ...baseLightMap, ...baseDarkJson, ...portfolioLightJson }
const portfolioDarkChanged = computeChangedTokens(portfolioDarkBaseMap, portfolioDarkJson)

validateTokenContract('tokens/brands/base/dark.json', 'mode')
validateTokenContract('tokens/brands/portfolio/dark.json', 'mode')

// ── base-light: the brand-agnostic foundation. Standalone-usable on its own —
// every semantic token resolves to a real neutral-gray value with no brand
// layered on top. ───────────────────────────────────────────────────────────
const baseLight = new StyleDictionary({
  usesDtcg: true,
  source: [
    'tokens/global.json',
    'tokens/components/*.json',
    'tokens/brands/base/light.json',
  ],
  platforms: {
    css: {
      transformGroup: 'css',
      prefix: '',
      buildPath: 'styles/brands/',
      files: [{
        destination: 'base-light.css',
        format: 'css/brand-variables',
        options: {
          brand: 'base',
          selector: ':root, [data-mode="light"]',
          // Late-bind semantic references: color-surface-primary: {color-neutral-50}
          // emits as var(--color-neutral-50) so it resolves against whichever layer
          // (base alone, or a brand overriding just the neutral primitives) is
          // active in the cascade, instead of baking in base's own gray value.
          preserveSemanticRefs: true,
        }
      }]
    }
  }
});

await baseLight.buildAllPlatforms();
console.log('✓ Built base-light.css');

// ── base-dark: brand-agnostic dark mode. ────────────────────────────────────
const baseDark = new StyleDictionary({
  usesDtcg: true,
  include: [
    'tokens/global.json',
    'tokens/components/*.json',
    'tokens/brands/base/light.json',
  ],
  source: [
    'tokens/brands/base/dark.json',
  ],
  platforms: {
    css: {
      transformGroup: 'css',
      prefix: '',
      buildPath: 'styles/brands/',
      files: [{
        destination: 'base-dark.css',
        format: 'css/brand-variables',
        filter: (token) => token.isSource || baseDarkChanged.has(token.name),
        options: { brand: 'base', selector: '[data-mode="dark"]', colorScheme: 'dark', preserveSemanticRefs: true }
      }]
    }
  }
});

await baseDark.buildAllPlatforms();
console.log('✓ Built base-dark.css');

// ── portfolio-light: brand overrides layered on base-light via cascade order
// (loaded after base-light.css in the consuming app/Storybook). Only the real
// differences — warm palette, Schibsted Grotesk, frozen-hero text, teal glow. ─
const portfolioLight = new StyleDictionary({
  usesDtcg: true,
  // Base tokens in `include` so SD understands portfolio/tokens.json intentionally
  // overrides them. Collision warnings only fire for source-vs-source conflicts;
  // include-vs-source is expected.
  include: [
    'tokens/global.json',
    'tokens/components/*.json',
    'tokens/brands/base/light.json',
  ],
  source: [
    'tokens/brands/portfolio/tokens.json',
  ],
  platforms: {
    css: {
      transformGroup: 'css',
      prefix: '',
      buildPath: 'styles/brands/',
      files: [{
        destination: 'portfolio-light.css',
        format: 'css/brand-variables',
        filter: (token) => token.isSource || portfolioLightChanged.has(token.name),
        options: { brand: 'portfolio', selector: ':root, [data-mode="light"]', preserveSemanticRefs: true }
      }]
    }
  }
});

await portfolioLight.buildAllPlatforms();
console.log('✓ Built portfolio-light.css');

// ── portfolio-dark: brand overrides on top of base-dark (loaded after both
// base-dark.css and portfolio-light.css). ───────────────────────────────────
const portfolioDark = new StyleDictionary({
  usesDtcg: true,
  include: [
    'tokens/global.json',
    'tokens/components/*.json',
    'tokens/brands/base/light.json',
    'tokens/brands/base/dark.json',
    'tokens/brands/portfolio/tokens.json',
  ],
  source: [
    'tokens/brands/portfolio/dark.json',
  ],
  platforms: {
    css: {
      transformGroup: 'css',
      prefix: '',
      buildPath: 'styles/brands/',
      files: [{
        destination: 'portfolio-dark.css',
        format: 'css/brand-variables',
        filter: (token) => token.isSource || portfolioDarkChanged.has(token.name),
        options: { brand: 'portfolio', selector: '[data-mode="dark"]', colorScheme: 'dark', preserveSemanticRefs: true }
      }]
    }
  }
});

await portfolioDark.buildAllPlatforms();
console.log('✓ Built portfolio-dark.css');

const { buildTokenReference } = await import('./scripts/build-token-reference.mjs');
buildTokenReference();

const { buildTokensJson } = await import('./scripts/build-tokens-json.mjs');
buildTokensJson();

const { buildComponentRegistry } = await import('./scripts/build-component-registry.mjs');
buildComponentRegistry();

// Depends on component-registry.json and token-reference.json, both already
// rebuilt above.
const { buildComponentDocs } = await import('./scripts/build-component-docs.mjs');
buildComponentDocs();

// Also depends on component-registry.json and token-reference.json.
const { buildRegistryManifests } = await import('./scripts/build-registry-manifests.mjs');
buildRegistryManifests();

// Also depends on component-registry.json and token-reference.json.
const { buildSkill } = await import('./scripts/build-skill.mjs');
buildSkill();

const { buildChangelog } = await import('./scripts/build-changelog.mjs');
buildChangelog();

// Must run last: llms.txt compiles from component-registry.json and
// token-reference.json, so both have to exist in their rebuilt form first.
const { buildLlmsTxt } = await import('./scripts/build-llms-txt.mjs');
buildLlmsTxt();
