// Stages a dist-like package for /design-sync (cfg.buildCmd).
//
// @amezquita/design-system ships TypeScript source with no build step and no
// barrel - consumers import components/<tier>/<Name> and their bundler
// compiles them. The design-sync converter wants what a published dist looks
// like: one entry module and a .d.ts tree. This script writes both into
// .design-sync/.cache/pkg/ (gitignored, rebuilt every sync) from the real
// source - nothing is reimplemented:
//
//   index.ts        barrel: `export *` from every public components/*/*/index.ts
//                   (BaseSheet is internal - Drawer's overlay primitive), plus
//                   the shipped stylesheets: base light/dark at :root (the
//                   white-label default), portfolio-scoped.css (opt-in via
//                   <ThemeScope brand="portfolio">), and reset.css.
//   types/          tsc declaration emit of components/ and lib/, with
//                   types/index.d.ts mirroring the barrel.
//   package.json    name/version from the repo root, types -> types/index.d.ts.
//
// Run from the repo root: node .design-sync/build-package.mjs

import { execFileSync } from 'node:child_process';
import { existsSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import { join, relative, resolve } from 'node:path';

const ROOT = resolve(import.meta.dirname, '..');
const OUT = join(ROOT, '.design-sync', '.cache', 'pkg');
const INTERNAL = new Set(['BaseSheet']);
const STYLESHEETS = [
  'styles/brands/base-light.css',
  'styles/brands/base-dark.css',
  'styles/brands/portfolio-scoped.css',
  'styles/reset.css',
];

const rootPkg = JSON.parse(readFileSync(join(ROOT, 'package.json'), 'utf8'));

rmSync(OUT, { recursive: true, force: true });
mkdirSync(OUT, { recursive: true });

const modules = [];
for (const tier of ['primitives', 'composition', 'patterns']) {
  for (const name of readdirSync(join(ROOT, 'components', tier)).sort()) {
    if (INTERNAL.has(name)) continue;
    if (!existsSync(join(ROOT, 'components', tier, name, 'index.ts'))) continue;
    modules.push(`components/${tier}/${name}`);
  }
}

const rel = (p) => relative(OUT, join(ROOT, p)).split('\\').join('/');
writeFileSync(join(OUT, 'index.ts'),
  '// Generated by .design-sync/build-package.mjs - do not edit.\n' +
  STYLESHEETS.map((s) => `import '${rel(s)}'`).join('\n') + '\n\n' +
  modules.map((m) => `export * from '${rel(m)}'`).join('\n') + '\n');

writeFileSync(join(OUT, 'package.json'), JSON.stringify({
  name: rootPkg.name,
  version: rootPkg.version,
  private: true,
  type: 'module',
  module: 'index.ts',
  types: 'types/index.d.ts',
}, null, 2) + '\n');

// Declarations: extend the repo tsconfig so path aliases and lib settings
// match what `npm run typecheck` sees; emit only .d.ts, stories/tests out.
writeFileSync(join(OUT, 'tsconfig.json'), JSON.stringify({
  extends: rel('tsconfig.json'),
  compilerOptions: {
    noEmit: false,
    declaration: true,
    emitDeclarationOnly: true,
    outDir: 'types',
    rootDir: rel('.'),
  },
  include: [`${rel('components')}/**/*`, `${rel('lib')}/**/*`],
  exclude: ['**/*.stories.tsx', '**/*.test.ts', '**/*.test.tsx', '**/__screenshots__/**', `${rel('lib')}/storybook.tsx`],
}, null, 2) + '\n');

execFileSync(join(ROOT, 'node_modules', '.bin', 'tsc'), ['-p', join(OUT, 'tsconfig.json')], { stdio: 'inherit', cwd: ROOT });

writeFileSync(join(OUT, 'types', 'index.d.ts'),
  modules.map((m) => `export * from './${m}'`).join('\n') + '\n');

console.log(`staged ${rootPkg.name}@${rootPkg.version}: ${modules.length} component modules -> ${relative(ROOT, OUT)}`);
