// Generated by scripts/build-theme-brands.mjs from the *-scoped.css files in
// styles/brands/. Do not edit: run `npm run tokens`.

/** The brands a ThemeScope can apply to part of a page: one per scoped brand file. */
export type ThemeBrand = 'portfolio'

export const THEME_BRANDS: readonly ThemeBrand[] = ['portfolio']
